### ISSUE TITLE
Support for MongoDB

### ISSUE THREAD

**Issue by jimthree** [richtr/baseapp#3]
Hi, as an enhancement would you consider implementing MongoDB (via https://labix.org/mgo) as one of the options for an auto-provisioned backend store?

**Comment by richtr** [comment]
This project uses https://github.com/go-gorp/gorp for Relational DB persistence.

MongoDB is a 'NoSQL' non-relational data store. I think it is unlikely that we (or https://github.com/go-gorp/gorp) will support MongoDB here.
